### ISSUE TITLE
Problems using it on ControlNet workflow

### ISSUE THREAD

**Issue by davizca** [Haoming02/comfyui-resharpen#1]
I have 2 controlNet before the prompt (one tile, one Hed), when I add the hook between prompt (which is null, I don't use any to test) and 1st controlnet (positive) it gives me 0 differente or even an error message. Did you try to use with a loaded image on img2img to see the effect?

**Comment by Haoming02** [comment]
Seems to work for me?

<p align="center"><b>Disabled</b><br>
<img src="https://github.com/Haoming02/comfyui-resharpen/assets/73768377/a0849e97-ced9-41cb-b277-6313d2e7c992" width=256>
</p>

<p align="center"><b>Enabled</b><br>
<img src="https://github.com/Haoming02/comfyui-resharpen/assets/73768377/df095bc2-97e8-4936-a44c-b8a63b9d870d" width=256>
</p>

**Comment by Haoming02** [comment]
Sample Workflow:
![Workflow](https://github.com/Haoming02/comfyui-resharpen/assets/73768377/7f7012cf-7f82-4e14-af09-93a85c49a9ee)

**Comment by Haoming02** [comment]
Ensure that:
1. The node is actually executed
2. You're not using an Ancestral sampler

**Comment by davizca** [comment]
Ei hi, totally right, My comfyUI was bugged, reinstall and updated and works. Thanks!
