### ISSUE TITLE
can't install via manager

### ISSUE THREAD

**Issue by AlexD81** [Haoming02/comfyui-resharpen#2]
Hi I'm getting following error if try to install via manager

_ComfyUI ReSharpen install failed: With the current security level configuration, only custom nodes from the "default channel" can be installed._

Updated and restarted comfy, but didn't help..  Probably it's not addon issue but dont know what to do with it

**Comment by Haoming02** [comment]
I just tried it, and it installed just fine using the `Custom Nodes Manager` in the **Manager**.

Please update your ComfyUI and Manager first~

**Comment by AlexD81** [comment]
tried again to update comfy and then install resharpen,  but problem is the same.   Don't know why

**Comment by Haoming02** [comment]
Welp, I'm out of idea then.

From some brief searching, most solutions only mentioned updating the Manager, or setting `disable_unsecure_features` to `True` in its config *(though not recommended)*.

And since this is a problem of the Manager, I'll close the issue then.

**Comment by AlexD81** [comment]
yea, it's definitely manager issue.  I've tried to update comfy for a maybe 10 times today,  it always shows no updates.   But on 11th,  it installed a lot of updates,  weird.       After this resharpen installed sucesfully, thanks
