### ISSUE TITLE
Please give info in description

### ISSUE THREAD

**Issue by Maelstrom2014** [Haoming02/comfyui-resharpen#3]
Please give info in description
1) What sd its used? 1.5, xl, 3 etc?
2) what samplers you recomend.

**Comment by Haoming02** [comment]
> SD

Any

> Samplers

Any, as long as not `Ancestral`

**Comment by Maelstrom2014** [comment]
> > SD
> 
> Any
> 
> > Samplers
> 
> Any, as long as not `Ancestral`

with xl it do absolutely nothing. I do it berween latent and ksampler.

**Comment by Haoming02** [comment]
Seems to work just fine?

<p align="center">
<img src="https://github.com/user-attachments/assets/2fcb7c53-f422-462c-9f48-dbfd986d2370">
</p>

**Comment by Maelstrom2014** [comment]
here is my:
![image](https://github.com/user-attachments/assets/c2389e29-85ac-438c-8285-2149fbea98cd)

**Comment by Maelstrom2014** [comment]
do almost nothing. what's the problem?
![image](https://github.com/user-attachments/assets/1dc7f19f-47a8-433b-8b2b-297547f8a152)

**Comment by Haoming02** [comment]
Hmm, perhaps it doesn't work with `Lightning` models?

Can you try with a regular checkpoint?
