### ISSUE TITLE
Blurry images when using Flux

### ISSUE THREAD

**Issue by wogam** [Haoming02/comfyui-resharpen#5]
Intermittently blurry images when using this with Flux. I think it may be related to some recent comfyui update as the issue wasn't here a week ago but I'm unable to debug it.

**Comment by Haoming02** [comment]
> the issue wasn't here a week ago 

Wait, you meant it used to work with Flux???

**Comment by wogam** [comment]
Yeah, it was definitely working with flux. It added a some uniform noise but also really helped with skin details, landscape details, etc. Idk what to say tbh, it just worked lol.

**Comment by Haoming02** [comment]
TIL 

~~Yes, I haven't tried it with Flux yet~~ 

I'll look into it

**Comment by Haoming02** [comment]
btw, may I ask which workflow are you using?

**Comment by Haoming02** [comment]
Using the [official workflow](https://comfyanonymous.github.io/ComfyUI_examples/flux/), I was able to get it work now.

Though I will have to experiment with the ***16*** channels more, cause the effect doesn't seem to be as strong as **SDXL** or **SD 1.5** right now...
