### ISSUE TITLE
the extension recognizes it as active but the changes are not applied.

### ISSUE THREAD

**Issue by artificail22** [Haoming02/comfyui-resharpen#7]
hi your extension is great i use it since automatic 1111 with difussion stable but now i am with comfyui with flux model using your node, the problem is that when i try to use the node in the terminal it comes out activated but when i finish the image it doesn't apply any change.

**Comment by Haoming02** [comment]
Seems to work for me:

<p align="center"><img src="https://github.com/user-attachments/assets/cd1e6b51-f4b0-495b-b6c3-c61b3e8ad2e3"></p>

Try a different **Sampler** if you are not using `Euler`. Also, **Flux** feels more sensitive to these changes. So maybe you have to increase/decrease the strength of the Node.

**Comment by artificail22** [comment]
Hello thank you for answering yes you are right the node works well in simple workflow with flux.

**Comment by artificail22** [comment]
before it also worked with DEIS-BETA sampler, I changed to EULER-SIMPLE sampler and it worked fine in my workflow, it is strange that it no longer works with DEIS-BETA sampler, it also gave good results
